name: Ping Render to Keep Alive

on:
  schedule:
    # Executa a cada 14 minutos para evitar que o serviço do Render "durma" (ele dorme com 15 minutos de inatividade)
    - cron: '*/14 * * * *'
  workflow_dispatch: # Permite que você também rode esse script manualmente

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Realizar ping na aplicação Render
        run: |
          # Faz o ping na aplicação para mantê-la ativa
          curl -s https://sistema-trader-4w6tle4xo-shaua-s-projects.vercel.app/ > /dev/null
          echo "Ping realizado com sucesso!"
